import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
sns.set_style('ticks')
weather = pd.read_csv('Weather.csv')
print(weather.head())
print(weather.info())
sns.barplot(x= weather['humidity'], y= weather['temperature'])
sns.distplot(weather['temperature'])
plt.show()
sns.displot(weather['temperature'], kde=False, rug=True)
plt.show()
sns.jointplot(x= weather['temperature'], y= weather['humidity'])
plt.show()
sns.jointplot(x= weather['temperature'], y= weather['humidity'], kind='hex')
plt.show()
sns.jointplot(x= weather['temperature'], y= weather['humidity'], kind='kde')
plt.show()
sns.stripplot(x= weather['temperature'], y= weather['humidity'])
plt.show()
sns.stripplot(x= weather['temperature'], y= weather['humidity'], jitter=True)
plt.show()
sns.swarmplot(x= weather['temperature'], y= weather['humidity'])
plt.show()
sns.barplot(x= weather['temperature'], y= weather['humidity'], hue=weather['weather_type'])
plt.show()
sns.countplot(x= weather['weather_type'])
plt.show()
sns.pointplot(x= weather['temperature'], y= weather['humidity'], hue=weather['weather_type'])
plt.show()