import sqlite3
database = 'databse.sqlite'
conn = sqlite3.connect(database)
print("Opened database successfully")
import pandas as pd
tables = pd.read_sql("SELECT * FROM sqlite_master WHERE type='table';", conn)
print(tables)
teams = pd.read_sql("SELECT * FROM teams;", conn)
print("\nTeams:")
print(teams.head())
matches = pd.read_sql("SELECT * FROM matches;", conn)
print("\nMatches:")
print(matches.head())
MI_wins = pd.read_sql("SELECT * FROM matches WHERE Match_Winner = 7;", conn)
print("\nMumbai Indians wins:")
print(MI_wins.head())
MI_58_59 = pd.read_sql("SELECT * FROM matches WHERE Match_Winner = 7 AND Season_ID IN (8, 9);", conn)
print("\nMumbai Indians wins season 8 and 9:")
print(MI_58_59.head())
new_team = pd.read_sql("SELECT * FROM teams WHERE Team_Name LIKE 'De%';", conn)
print("\nTeams starting with De:")
print(new_team.head())
min_max_margin = pd.read_sql("SELECT MIN(Match_Margin) AS Win_Margin, MAX(Match_Margin) FROM matches;", conn)
print("\nMinimum and Maximum Match Margin:")
print(min_max_margin)
conn.close()
print("\nDatabase closed")