import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statisctics as std
df = pd.read_csv('Students_Performance.csv')
print(df.head())
print(df.info())
print(df.isnull().any())
print(df.isnull().sum())
labels = ["math score", "reading score", "writing score"]
for label in labels:
    median_label = np.median(df[label])
    mean_label = np.mean(df[label])
    mode_label = std.mode(df[label])
    print(f'Label: {label}')
    print(f'  Median: {median_label}')
    print(f'  Mean: {mean_label}')
    print(f'  Mode: {mode_label}')
labels1 = ['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course']
for label in labels1:
    sns.countplot(data=df, x=label, palette='Set2')
    plt.title(f'Bar Chart of {label}', fontsize=14, fontweight='bold')
    plt.xlabel(label, fontsize=12)
    plt.ylabel('Count', fontsize=12)
    plt.xticks(rotation=45)
    plt.show()
race_counts = df['race/ethnicity'].value_counts()
plt.pie(race_counts, labels=race_counts.index, autopct='%.1f%%', colors=['lightcoral', 'lightblue', 'lightgreen', 'lightyellow', 'lightpink'], startangle=90)
plt.title('Pie Chart of Race/Ethnicity')
plt.axis('equal')
plt.show()
education_counts = df['parental level of education'].value_counts()
plt.pie(education_counts, labels=education_counts.index, autopct='%.1f%%', colors=['lightcoral', 'lightblue', 'lightgreen', 'lightyellow', 'lightpink'], startangle=90)
plt.title('Pie Chart of Parental Level of Education')
plt.axis('equal')
plt.show()
sns.countplot(data=df, x=df['race/ethnicity'], hue=df['gender'], palette='Set2')
plt.title('Count Plot of Race/Ethnicity by Gender')
plt.xlabel('Race/Ethnicity')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()
sns.countplot(data=df, x=df['lunch'], hue=df['gender'], palette='Set2')
plt.title('Count Plot of Lunch by Gender')
plt.xlabel('Lunch') 
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()
association = pd.crosstab(df['gender'], df['math score'])
sns.heatmap(association, annot=True, cmap='YlGnBu')
plt.title('Heatmap of Gender and Maths Score')
plt.xlabel('Maths Score')
plt.ylabel('Gender')
plt.show()