import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import numpy as np
df = pd.read_csv('IMDB_Dataset.csv')
print(df.head(10))
print(df.tail(10))
print(df.isnull().sum())
sns.histplot(data=df['Runtime'], bins=np.arange(1, 101, 20), color='black', edgecolor='red')
plt.xlabel('Runtime (minutes)')
plt.ylabel('Count of Movies')
plt.show()
sns.histplot(data=df['IMDB_Rating'], bins=np.arange(1, 11, 2), color='blue', edgecolor='red')
plt.xlabel('IMDB Rating')
plt.ylabel('Count of Movies')
plt.show()
df['Runtime'].unique()
bins_time = np.arange(80, 230, 10)
sns.histplot(data=df['Runtime'], bins=bins_time, color='green', edgecolor='red')
plt.xlabel('Runtime (minutes)')
plt.ylabel('Count of Movies')
plt.show()
df['IMDB_Rating'].unique()
bins_rating = np.arange(8, 10, 0.20)
sns.histplot(data=df['IMDB_Rating'], bins=bins_rating, color='orange', edgecolor='red')
plt.xlabel('IMDB Rating')
plt.ylabel('Count of Movies')
plt.xticks(bins_rating)
plt.show()