import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import statistics as stats
df = pd.read_csv('Bestsellers_with_categories.csv')
print(df.head())
print(df.describe())
print(df.info())
print(df.isnull().sum())
mean_price = np.mean(df['Price'])
print(f'Mean Price: {mean_price}')
median_price = np.median(df['Price'])
print(f'Median Price: {median_price}')
mode_price = stats.mode(df['Price'])
print(f'Mode Price: {mode_price}')
mean_year = np.mean(df['Year'])
print(f'Mean Year: {mean_year}')
mean_year = np.median(df['Year'])
print(f'Median Year: {mean_year}')
mode_year = stats.mode(df['Year'])
print(f'Mode Year: {mode_year}')
mean_user_rating = np.mean(df['User Rating'])
print(f'Mean User Rating: {mean_user_rating}')
median_user_rating = np.median(df['User Rating'])
print(f'Median User Rating: {median_user_rating}')
mode_user_rating = stats.mode(df['User Rating'])
print(f'Mode User Rating: {mode_user_rating}')
mean_reviews = np.mean(df['Reviews'])
print(f'Mean Reviews: {mean_reviews}')
median_reviews = np.median(df['Reviews'])
print(f'Median Reviews: {median_reviews}')
mode_reviews = stats.mode(df['Reviews'])
print(f'Mode Reviews: {mode_reviews}')