import statistics as stats
import pandas as pd
import numpy as np
df = pd.read_csv('Titanic_Dataset.csv')
print(df.head(10))
print(df.tail(10))
print(df.columns)
print(df.isnull().sum())
print(df.isnull().any())
print(df.dtypes)
mean_age = np.mean(df['Age'])
print("Mean Age:", mean_age)
mean_fare = np.mean(df['Fare'])
print("Mean Fare:", mean_fare)
median_age = np.median(df['Age'])
print("Median Age:", median_age)
median_fare = np.median(df['Fare'])
print("Median Fare:", median_fare)
mode_age = stats.mode(df['Age'])
print("Mode Age:", mode_age)
mode_fare = stats.mode(df['Fare'])
print("Mode Fare:", mode_fare)
mode_class = stats.mode(df['Pclass'])
print("Mode Class:", mode_class)
mode_gender = stats.mode(df['Gender'].value_counts().index[0])
print("Mode of Gender:", mode_gender)